const EntidadeSinc = require('../lib_react_backend/sincronizacao/EntidadeSinc');
const field = require('../lib_react_backend/sincronizacao/field');

module.exports = (class Cidade extends EntidadeSinc {

  constructor() {
    super('tab_cidade');
  }

  getFields() {
    return [
      field('cod_cidade').pk(),
      field('cod_estado').int(6),
      field('cidade').varchar(255),
      field('cod_ibge').int(2),
    ];
  }

  getReferences() {
    return [
      field('cod_estado').references('tab_estado(cod_estado)', 'cidade_estado'),
    ];
  }
  
  getDefaults() {
    return [
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'PARANAVAÍ', 4118402);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (26, 'RIO BRANCO', 1200401);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (26, 'SENA MADUREIRA', 1200500);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (26, 'ASSIS BRASIL', 1200054);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'CALIFORNIA', 4103503);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (26, 'PLÁCIDO DE CASTRO', 1200385);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (26, 'BRÁSILEIA', 1200104);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'CRUZEIRO DO SUL', 4106704);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (4, 'CHAPECÓ', 4204202);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'ROSANA', 3544251);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'ALTO PARANÁ', 4100608);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'ALTO PIQUIRI', 4100707);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'ALTÔNIA', 4100509);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'ANGULO', 4101150);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'APUCARANA', 4101408);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'ARAPUA', 4101655);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'ARARUNA', 4101705);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'ASSAI', 4101903);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'ASSIS CHATEAUBRIAND', 4102000);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'ASTORGA', 4102109);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'ATALAIA', 4102208);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'BANDEIRANTES', 4102406);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'BARBOSA FERRAZ', 4102505);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'BOA ESPERANÇA', 4103008);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'BOM SUCESSO', 4103206);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'BORRAZÓPOLIS', 4103305);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'CAMBARA', 4103602);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'CAMBÉ', 4103701);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'CAMPINA DA LAGOA', 4103909);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'CAMPO MOURÃO', 4104303);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'CANDIDO DE ABREU', 4104402);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'CARAMBEI', 4104659);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'CASTRO', 4104907);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'CENTENÁRIO DO SUL', 4105102);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'CIANORTE', 4105508);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'CIDADE GAÚCHA', 4105607);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'COLORADO', 4105904);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'CORBELIA', 4106308);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'CRUZEIRO DO OESTE', 4106605);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'CURITIBA', 4106902);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'DIAMANTE DO NORTE', 4107108);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'DOURADINA', 4107256);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'ENGENHEIRO BELTRÃO', 4107504);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'EUCLIDES DA CUNHA PAULISTA', 3515350);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'FLORAÍ', 4107801);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'FLORESTOPOLIS', 4108007);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'FORMOSA DO OESTE', 4108205);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'FRANCISCO ALVES', 4108320);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'GOIOERÊ', 4108601);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'GUAIRAÇÁ', 4108908);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'GUARACI', 4109203);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'GUARANIAÇU', 4109302);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'IBIPORÃ', 4109807);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'ICARAIMA', 4109906);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'IPAUSSU', 3520905);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'IPORA', 4110607);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'IRETAMA', 4110805);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'ITAGUAJE', 4110904);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'ITAMBÉ', 4111100);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'ITAUNA DO SUL', 4111308);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'IVAIPORA', 4111506);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'IVATE', 4111555);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'JACAREZINHO', 4111803);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'JANDAIA DO SUL', 4112108);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'JANIOPOLIS', 4112207);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'JAPURA', 4112405);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'JARDIM ALEGRE', 4112504);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'JATAIZINHO', 4112702);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'JESUITAS', 4112751);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'JURANDA', 4112959);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'JUSSARA', 4113007);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'LOANDA', 4113502);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'LOBATO', 4113601);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'LONDRINA', 4113700);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'LUPIONOPOLIS', 4113809);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'MAMBORE', 4114005);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'MANOEL RIBAS', 4114500);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'MARILENA', 4115002);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'MARILUZ', 4115101);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'MARINGA', 4115200);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'MOREIRA SALES', 4116109);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'MUNHOZ DE MELO', 4116307);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'NOVA AMERICA DA COLINA', 4116604);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'NOVA CANTU', 4116802);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'NOVA ESPERANÇA', 4116901);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'NOVA FATIMA', 4117008);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'NOVA LONDRINA', 4117107);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'NOVA OLIMPIA', 4117206);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'OURINHOS', 3534708);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'OURIZONA', 4117404);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'PALMITAL', 4117800);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'PARAISO DO NORTE', 4118006);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'PARANACITY', 4118105);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'PEABIRU', 4118808);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'PEROLA', 4118907);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'PITANGA', 4119608);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'PLANALTINA DO PARANA', 4119707);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'PONTA GROSSA', 4119905);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'PORECATU', 4120002);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'PORTO RICO', 4120200);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'PRESIDENTE CASTELO BRANCO', 4120408);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'PRIMAVERA', 3544251);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'SALTO DO ITARARÉ', 4122909);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'IBAITI', 4109708);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'RESERVA', 4121703);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'RONCADOR', 4122503);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'RONDON', 4122602);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'SANTA CRUZ DE MONTE CASTELO', 4123303);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'SANTA FE', 4123402);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'SANTA ISABEL DO IVAI', 4123709);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'SANTO ANASTACIO', 3547700);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'SANTO INACIO', 4124509);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'SÃO CARLOS DO IVAI', 4124608);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'SÃO JOÃO DO CAIUÁ', 4124905);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'SÃO JOÃO DO IVAÍ', 4125001);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'SÃO PEDRO DO IVAI', 4125803);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'TAPEJARA', 4126801);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'TERRA BOA', 4127205);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'TERRA RICA', 4127304);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'TERRA ROXA', 4127403);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'TUNEIRAS DO OESTE', 4127908);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'TUPASSI', 4127957);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'UBIRATA', 4128005);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'UMUARAMA', 4128104);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'URAI', 4128401);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'ALTO PARAÍSO', 4128104);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'XAMBRE', 4128807);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'SÃO CAETANO DO SUL', 3548807);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (9, 'CACHOEIRINHA', 4303103);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'DIADEMA', 3513801);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'SERTANÓPOLIS', 4126504);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'SALTO', 3545209);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'JUNDIAÍ', 3525904);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'SANTO ANDRÉ', 3547809);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'CASCAVEL', 4104808);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'PALOTINA', 4117909);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'MOGI GUAÇÚ', 3530706);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'COTIA', 3513009);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'MARUMBI', 4115507);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'TOLEDO', 4127700);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'MEDIANEIRA', 4115804);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'GUAÍRA', 4108809);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'FAXINAL', 4107603);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'VINHEDO', 3556701);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'ALVORADA DO SUL', 4100806);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'AMAPORÃ', 4100905);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'BELA VISTA DO PARAÍSO', 4102802);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'GUARULHOS', 3518800);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'SÃO JORGE DO PATROCÍNIO', 4125357);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'CORNÉLIO PROCÓPIO', 4106407);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'SANTA CECÍLIA DO PAVÃO', 4123204);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'NOVA SANTA BARBARA', 4117214);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'INÁCIO MARTINS', 4110201);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'ALTO PARAÍSO', 4128625);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'ANDIRÁ', 4101101);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'CORUMBATAÍ DO SUL', 4106555);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'SÃO JOSÉ DO RIO PRETO', 3549805);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'PIRAPOZINHO', 3539202);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'SÃO JERÔNIMO DA SERRA', 4124707);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'SÃO SEBASTIÃO DA AMOREIRA', 4126009);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'SÃO MIGUEL DO IGUAÇU', 4125704);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'SÃO JORGE DO IVAÍ', 4125308);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'SÃO TOMÉ', 4126108);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'SÃO LOURENÇO', 4105508);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'RIBEIRÃO PRETO', 3543402);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (9, 'ERECHIM', 4307005);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'MAIRIPORÃ', 3528502);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'ITAQUERA', 3550308);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'NOVA SANTA ROSA', 4117222);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'KALORÉ', 4113106);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'TABOÃO DA SERRA', 3552809);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'BAURU', 3506003);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'SANTANA DE PARNAIBA', 3547304);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'TELEMÂCO BORBA', 4127106);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'CARAGUATATUBA', 3510500);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'CAFELÂNDIA', 4103453);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'CERQUEIRA CESAR', 3511409);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'ARANDÚ', 3503109);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'AVARÉ', 3504503);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'QUERÊNCIA DO NORTE', 4121000);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'PRESIDENTE VENCESLAU', 3541505);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'PRESIDENTE EPITÁCIO', 3541307);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'PIQUEROBI', 3538303);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'ITAMBARACÁ', 4111001);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'TEODORO SAMPAIO', 3554300);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'QUINTA DO SOL', 4121109);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'PRESIDENTE PRUDENTE', 3541406);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'SÃO BERNARDO DO CAMPO', 3548708);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'IBEMA', 4109757);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'SÃO JOSÉ DAS PALMEIRAS', 4125456);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (7, 'CAMPO NOVO DO PARECIS', 5102637);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'FARTURA', 3515400);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'ITAI', 3521804);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'LARANJEIRAS DO SUL', 4113304);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'NOVA TEBAS', 4117271);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'VALINHOS', 3556206);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'SANTA HELENA', 4123501);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'ITAQUAQUECETUBA', 3523107);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (8, 'IGUATEMI', 5004304);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'FIGUEIRA', 4107751);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (8, 'PARANHOS', 5006358);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'WENCESLAU BRAZ', 4128500);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (8, 'NOVA ANDRADINA', 5006200);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'IMBITUVA', 4110102);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'PIRAÍ DO SUL', 4119400);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'NOVA LARANJEIRAS', 4117057);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (8, 'ELDORADO', 5003751);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (8, 'MUNDO NOVO', 5005681);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (8, 'ITAQUIRAI', 5004601);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'IGARATÁ', 3520202);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'CARLOPOLIS', 4104709);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (8, 'DOURADOS', 5003702);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'IPIRANGA', 4110508);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (8, 'NAVIRAÍ', 5005707);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (4, 'SIDERÓPOLIS', 4217600);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (8, 'AMAMBAÍ', 5000609);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (8, 'SETE QUEDAS', 5007703);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'ARUJÁ', 3503901);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'ASSIS', 3504008);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'JAGUARIAIVA', 4112009);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'GARÇA', 3516705);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'BERNARDINO DE CAMPOS', 3506300);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'NOVA AURORA', 4116703);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'ALTAMIRA DO PARANÁ', 4100459);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'VERA CRUZ', 3556602);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'PRUDENTÓPOLIS', 4120606);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'MATELÂNDIA', 4115606);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'TAMARANA', 4126678);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (8, 'TACURU', 5007950);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'SERTANEJA', 4126405);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'SANTA CRUZ DO RIO PARDO', 3546405);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (19, 'ARARIPE', 2301307);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'SAPOPEMA', 4126207);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'MARILIA', 3529005);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'CAIEIRAS', 3509007);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'TRÊS BARRAS DO PARANA', 4127858);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'CANTAGALO', 4104451);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'GUARAPUAVA', 4109401);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'PINHAO', 4119301);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'BOA VENTURA DE SAO ROQUE', 4103040);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'ARAUCÁRIA', 4101804);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'SANTO AMARO', 3550308);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'TURVO', 4127965);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'FOZ DO JORDAO', 4108452);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'SÃO PAULO', 3550308);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'CAMPINAS', 3509502);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'PARQUE CAPUAVA', 3550308);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'RIO BRANCO DO IVAI', 4122172);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'CAMPINA DO SIMAO', 4103958);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'PIRITUBA', 3550308);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'CIDADE JARDIM', 3550308);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'LOUVEIRA', 3527306);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'IRATI', 4110706);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'DIADEMA', 3513801);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'TAMBOARA', 4126702);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'LEME', 3526704);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'LEME', 3526704);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'MAUÁ', 3529401);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (6, 'RIO BONITO', 3304300);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'RIO BONITO DO IGUAÇU', 4122156);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'UNIFLOR', 4128302);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'MALLET', 4113908);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'CANDOI', 4104428);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (11, 'APARECIDA DE GOIANIA', 5201405);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'CRUZ MACHADO', 4106803);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'FAXINAL DO CÉU', 4107603);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'GOIOXIM', 4108650);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'CRAVINHOS', 3513108);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'TIBAGI', 4127502);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (9, 'PORTO ALEGRE', 4314902);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (4, 'BALNEARIO CAMBORIU', 4202008);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'BITURUNA', 4102901);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'RIO AZUL', 4122008);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'LIDIANOPOLIS', 4113429);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'QUEDAS DO IGUAÇU', 4120903);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'MARIALVA', 4114807);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (21, 'RECIFE', 2611606);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'TAPIRA', 4126900);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'DIADEMA', 3513801);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'PRUDENTÓPOLIS', 4120606);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'UNIAO DA VITORIA', 4128203);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'BRAGANEY', 4103354);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'PALMEIRA', 4117701);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'SANTA LUCIA', 4123824);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'CAPANEMA', 4104501);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'INAJÁ', 4110300);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'MARIPA', 4115358);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'VIRMOND', 4128658);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'CASA VERDE', 3550308);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'ITUPEVA', 3524006);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'ARIRANHA DO IVAI', 4101853);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'ROSA HELENA', 0);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'ROSARIO DO IVAI', 4122651);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'VILA ALTA', 0);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (4, 'BRUSQUE', 4202909);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'PINHAIS', 4119152);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'RIBEIRÃO PIRES', 3543303);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (9, 'CAXIAS DO SUL', 4305108);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'FERRAZ DE VASCONCELOS', 3515707);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'MANGUEIRINHA', 4114401);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (8, 'CAMPO GRANDE', 5002704);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'INDIANOPOLIS', 4110409);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'SUZANO', 3552502);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'MARECHAL CANDIDO RONDON', 4114609);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'UBIRATÃ', 4128005);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (6, 'NOVA FRIBURGO', 3303401);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'OSASCO', 3534401);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (11, 'GOIANIA', 5208707);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'MANDAGUAÇU', 4114104);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (4, 'CRICIUMA', 4204608);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'BARUERI', 3505708);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'SÃO CAETANO DO SUL', 3548807);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'CAFEZAL DO SUL', 4103479);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'IVAI', 4111407);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'SALTO DO LONTRA', 4123006);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'VARZEA PAULISTA', 3556503);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'PLANALTO', 4119806);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (4, 'JOINVILLE', 4209102);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'COLOMBO', 4105805);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'RIO BRANCO DO SUL', 4122206);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'FÊNIX', 4107702);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'PEROBAL', 4118857);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'MATINHOS', 4115705);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'IPERÓ', 3521002);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'ARARAQUARA', 3503208);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'SOROCABA', 3552205);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'RANCHO ALEGRE D\OESTE', 4121356);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'ARAPONGAS', 4101507);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'JAGUAPITÃ', 4111902);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'SERRA DOS DOURADOS', 4126355);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (4, 'TIJUCAS', 4218004);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'FAROL', 4107553);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'CARAPICUÍBA', 3510609);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'SABAUDIA', 4122701);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'CAJAMAR', 3509205);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'GUARATUBA', 4109609);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'SAO JOSE DOS PINHAIS', 0);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'PALMAS', 4117602);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'BRASILANDIA DO SUL', 4103370);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'MORRETES', 4116208);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'ROSANA', 4100608);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'EMBU DAS ARTES', 3515004);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (8, 'PARANAÍBA', 5006309);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'EUCLIDES DA CUNHA', 4100608);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'MARIA HELENA', 4114708);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'LUNARDELLI', 4113759);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'AMPÉRE', 4101002);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (1, 'SãO MATEUS DO SUL', 4125605);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'SAO CARLOS', 3548906);`,
      ` INSERT INTO tab_cidade (cod_estado, cidade, cod_ibge) VALUES (3, 'BRAGANÇA PAULISTA', 3507605);`,
    ];
  }
});
