const EntidadeSinc = require('../lib_react_backend/sincronizacao/EntidadeSinc');
const field = require('../lib_react_backend/sincronizacao/field');

module.exports = (class Medicamento extends EntidadeSinc {

  constructor() {
    super('tab_medicamento');
  }

  getFields() {
    return [
      field('cod_medicamento').pk(),
      field('cod_funcionario').int(11),
      field('nome_medicamento').varchar(255),
      field('observacao').varchar(255),
      field('uso').varchar(50),
      field('forma').varchar(50),
      field('quantidade').varchar(50),
      field('posologia_1').varchar(130),
      field('posologia_2').varchar(130),
      field('posologia_3').varchar(130),
      field('posologia_4').varchar(130),
      field('posologia_5').varchar(130),
      field('tp_medicamento').enum('N', 'A').default('N'),
      field('tipo').enum('D', 'M').default('D'),
    ];
  }

  getReferences() {
    return [
      field('cod_funcionario').references('tab_funcionario(cod_funcionario)', 'medicamento_funcionario'),
    ];
  }
  
  getDefaults() {
    return [
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (1, 'CLAVULIN ES (600MG+42,9MG/5ML)', 'OBSERVA', 'INTERNO', 'POMADA', '1 FR 100ML', 'TOMAR      A CADA 12 HS, 2X AO DIA, 10 DIAS.A PARTIR DE 3M DE IDADE.', 'SIMPLESMENTE TOMA', 'TOMAR SEMPRE', 'EU QUERO QUE VOCÊ TOMA O REMÉDIO', 'SE NÃO QUISER, NÃO TOMA', 'A', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (2, 'PREDSIM 40', NULL, 'INTERNO', NULL, '1 CX', 'TOMAR 1 CP AO DIA, 5 DIAS', NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (2, 'GABAPENTINA 300', NULL, 'INTERNO', NULL, '02 CX', 'TOMAR 1 CP ATE 3X AO DIA', NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (3, 'MUD ORAL', NULL, 'ORAL', NULL, '1 BISNAGA', 'COLOCAR SOBRE AFTAS OU LESOES DA BOCA 3X AO DIA', NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (2, 'OTO BETNOVATE', NULL, 'OTOLOGICO', NULL, '1 FR', 'PINGAR 3 GTS EM CADA OUVIDO 2X AO DIA', NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (2, 'FLIXOTIDE 50 COM ESPAÇADOR', NULL, 'INALACAO ORAL', NULL, '1 FR', 'APÓS HIGIENIZAR ESPAÇADOR, INSTALAR O FLIXOTIDE, FAZER 2 APLICACOES E ASPIARAR', 'COMPASSADAMENTE CONTANDO ATÉ 10. FAZER ESTE PROCEDIMENTO A CADA 8 HS, 3X AO DIA,', 'ÁTÉ MELHORAR A TOSSE.', NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (3, 'SINNOT-CLAV 400MG,SIGMA-CLAV 400MG,NOVAMOX 400MG, CLAVULIN 400MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (2, 'VIATINE 4MG, 5 MG, 10 MG (SINGULAIR)', NULL, 'INTERNO', NULL, '3 CX', 'TOMAR 1 CP AO DEITAR, 90 DIAS', NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (2, 'ALENIA 6/200', NULL, 'ORAL', NULL, '1 CX', 'ASPIRAR 1 CPS 2X AO DIA.', NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (2, 'NIFEDIPINA 2% LIDOCAÍNA 1,5% VITAL ET 2% ÓXIDO DE ZINDO 20% HIDROCORTISONA 1% NANOMELALEUCA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A', 'M');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (3, 'LACTOSIL 10000 FCC ALU', NULL, 'INTERNO', NULL, '1 CX', 'TOMAR 1 SACHE AO USAR O ALIMENTO OU SOBRE ELE.', NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (2, 'LACTOSIL 4000 FCC ALU', NULL, 'INTERNO', NULL, '1 CX', 'ASSOCIAR O USO AO ALIMENTO COM LACTOSE.', NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (2, 'LACRIMA', NULL, 'OCULAR', NULL, '1 FR', 'INSTILAR 2 GTS EM OLHO A CADA 6 HS', NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (2, 'POMADA DE NIFEDIPINA', 'POMADA DE NIFEDIPINA', 'TÓPICO', 'POMADA', ' 50 ', 'NIFEDIPINA 2% + LIDOCAINA 1.5% + VITAL E.T. 2% + ÓXIDO DE ZINCO 20%+ ', 'D PANTENOL 2% + NANOMELALEUCA 0,5% + AFGF 1,5% + IGF2% + POMADA DE ', 'MEL MODIFICADA 50 gr. - APLICAR  NO  LOCAL AFETADO 2 X AO DIA ', NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (3, 'ALVESCO 160 MCG/DOSE', NULL, 'INALATÓRIO', NULL, '1 FR', 'ASPIRAR 2 PUFSS 2X AO DIA.', NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (2, 'CLINARIS JATO SPRAY CONTINUO', NULL, 'NASAL', NULL, '1 FR', 'APLICAR NAS NARINAS VÁRIAS VEZES AO DIA', NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (2, 'DRAMIN 25 MG CAPSGEL ', NULL, 'INTERNO', NULL, '1 CX', 'TOMAR 1 CPS GELATINOSA ATÉ 2X AO DIA, PODE SER USADO EM CRIANÇAS DE 6 A 12 ANOS', NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (2, 'DRAMIN 50 MG CAPSGEL', NULL, 'INTERNO', NULL, '1 CX', 'TOMAR 1 CPS ATÉ 2X AO DIA', NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (2, 'VACINA ANTIGRIPAL(ANTI H1N1)', NULL, 'EXTERNO', NULL, '1 FRAMP', 'APLICAR IM', NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (3, 'ADIPEPT 20 (PANTOPRAZOL)', NULL, 'INTERNO', NULL, '1 CX', 'TOMAR 1 CP ANTES DO CAFÉ DA MANHÃ,', NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (2, 'CHAMPIX 0,5', NULL, 'INTERNO', NULL, '1 CX', 'TOMAR 1 CP APÓS CAFÉ DA MANHÃ, 3 DIAS.', 'APÓS, TOMAR 1 CP 2X AO DIA, APÓS CAFÉ DA MANHÃ E JANTAR, 4 DIAS.', 'CONTINUAR COM CHAMPIX 1 MG  2X AO DIA.', NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (2, 'CHAMPIX 1 MG (TARTARATO DE VARENICLINA)', NULL, 'INTERNO', NULL, '2 CX', 'TOMAR 1 CP APÓS CAFÉ DA MANHÃ E JANTAR, POR 12 SEMANAS.', 'TOMAR NOS MESMOS HORÁRIOS EM QUE FAZIA USO DO CHAMPIX 0,5MG', 'CASO APÓS 12 SEMANAS TENHA PARADO DE FUMAR, MANTER 1 CP 2X AO DIA,', 'MAIS 12 SEMANAS.', NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (2, 'LIDOSPORIN', NULL, 'OTOLÓGICO', NULL, '1 FR', 'PINGAR 3 GTS NO OUVIDO COM DOR.', NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (2, 'UM BI (PROBIOTICO) SACHES', NULL, 'INTERNO', NULL, '1 CX', 'TOMAR O CONTEUDO DO SACHE 1X AO DIA', NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (3, '20 BI ( PROBIOTICO)', NULL, 'INTERNO', NULL, '1 CX', 'tOMAR 1 CPS  AO DIA,', NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (2, 'STIMULANCE', NULL, 'INTERNO', 'PÓ', '20 SACHES', 'TOME 1 SACHE POR DIA.', NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (2, 'TAMIFLU 75, 45, 30 MG', NULL, 'INTERNO', NULL, '1 CX', 'ADULTOS. 1 CP 2X AO DIA, 5 DIAS', 'MENORES DE 15 KG- 30 MG 2X AO DIA, 5 DIAS( DISSOLVER EM AGUA', 'ENTRE 15 E 23 KG- 45 MG 2X AO DIA, 5 DIAS', 'ENTRE 23 E 40 KG, 60 MG 2X AO DIA. ACIMA DE 40 KG 75MG 2X AO DIA, 5 DIAS', NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (2, 'PROTECT USO ADULTO( BETA-GLUCANA)', NULL, 'INTERNO', NULL, '03 CX', 'DISSOLVER 1 SACHE EM UM COPO DE ÁGUA E TOMAR 1X AO DIA, NO MINIMO POR 90 DIAS', NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (2, 'PROTECT USO INFANTIL', NULL, 'INTERNO', NULL, '03 CX', 'DISSOLVER O SACHE EM UM COPO DÁGUA, TOMAR 1X AO DIA, 60 DIAS.', NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (3, 'TAMIFLU (OZELTAMIVIR)', NULL, 'INTERNO', 'COMPRIMIDO', '10 COMPRIMIDOS', 'DILUIR 1 COMPRIMIDO EM 10 ML DE ÁGUA.', 'TOME   ML DE 12 / 12 HORAS, DURANTE 5 DIAS.', NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (2, 'INIPARET ( RABEPRAZOL ) 20', NULL, 'INTERNO', NULL, '1 CX', 'TOMAR 1 CP ANTES DO CAFÉ DA MANHÃ', NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (2, 'PNEUMO13', NULL, 'EXTERNO', NULL, '1 AMP', 'APLICAR IM', NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (2, 'ZYBAM 150', NULL, 'INTERNO', NULL, '03 CX', 'TOMAR 1 CP PELA MANHÃ, 7 DIAS.', 'APÓS, TOMAR 1 CP 2X AO DIA, 8 SEMANAS', NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (3, 'CERUMIN', NULL, 'TÓPICO', 'SOLUÇÃO', '1 FRASCO', 'PINGAR 1 GOTA EM CADA OUVIDO 1 X AO DIA.', NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (2, 'SIMBIOFLORA', NULL, 'INTERNO', 'SACHE', '01CX', 'TOME 01 ENVELOPE  DILUIDO EM 1/2  COPO DE AGUA  DURANTE O ALMOÇO E JANTAR ', 'POR 3  DIAS, APOS  SOMENTE  NO ALMOÇO.', NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (2, 'ADIPEPT 40', NULL, 'INTERNO', 'CPS', '01CX', 'TOME 01 PELA  MANHA  JEJUM', NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (2, 'MARESIS JATO FORTE', NULL, 'NASAL', NULL, '1 FR', 'APLICAR NAS NARINAS VARIAS VEZES AO DIA', NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (3, 'MARESIS JATO SUAVE', NULL, 'NASAL', NULL, '1 FR', 'APLICAR NAS NARINAS VÁRIAS VEZES AO DIA', NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (2, 'MIOFLEX A', NULL, 'INTERNO', NULL, '1 CX', 'TOMAR 1 CP AO DEITAR', NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (2, 'PARALAC', NULL, 'INTERNO', NULL, '1 CX', 'INGERIR 1 CP ANTES DO ALIMENTO COM LACTOSE', NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (2, 'ATAK CLAV 400MG+57MG/5ML', NULL, 'INTERNO', NULL, '1 FR', 'TOMAR   ML A CADA 12 HS, 2X AO DIA, 10 DIAS', NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (2, 'ATAK CLAV 875MG+125MG', NULL, 'INTERNO', NULL, '20 CPS', 'TOMAR 1 CP A CADA 12 HS, 2X AO DIA, 10 DIAS.', NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (3, 'GÁZIA 40MG- PANTOPRAZOL', NULL, 'INTERNO', NULL, '', 'TOMAR 1 CP ANTES DO CAFÉ DA MANHA', NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (2, 'DECADRON NASAL', NULL, 'NASAL', NULL, '1 FR', 'PINGAR 3 GTS EM CADA NARINA 3X AO DIA, 5 DIAS', NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (2, 'TAMIRAM 750', NULL, 'INTERNO', NULL, '1 CX', 'TOMAR 1 CP APÓS JANTAR, 5 DIAS', NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (2, 'PERLATTE (ASPERGILLUS ORYZAE)', NULL, 'INTERNO', NULL, '1 CX', 'TOMAR 1 CP ANTES DO ALIMENTO LACTEO9 TEM DURACAO DE ATE 3 HS)', NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (3, 'ESOMEX 40 MG', NULL, 'INT', 'COMP.', '28 CP ', 'TOMAR 1 CP 30 MIN. ANTES DO CAFÉ DA MANHÃ', NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (3, 'LONIUM 40 MG', NULL, 'INT', 'CP', ' 1 CX', 'TOME  1 CP APÓS O CAFÉ , ALMOÇO E JANTAR ', NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (3, 'DIGEDRAT 200 MG', NULL, 'INT', 'CP', ' 1 CX', 'TOME  1 DRÁGEA APÓS O CAFÉ E JANTAR ', NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (3, 'INIPARET 20 MG', NULL, 'INT', 'CP', '28 CP', 'TOMAR 1 CP 30 MIN. ANTES DO CAFÉ DA MANHÃ', NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (3, 'TRIMEB 200 MG', NULL, 'INT', 'CP', ' 1 CX', 'TOME  1 CP APÓS O CAFÉ DA MANHÃ E JANTAR ', NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (3, 'ESOGASTRO IBP 28', NULL, 'INT', 'CP', ' 1 CX', 'TOME 4 CP 30 MIN. ANTES DO CAFÉ DA MANHÃ E JANTAR POR 7 DIAS . APÓS TOMAR ', '1 CP DE ESOMEPRAZOL 20 MG , 30 MIN. ANTES DO CAFÉ DA MANHÃ POR MAIS 28 DIAS ', NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (3, 'DOMPERIX 10 MG', NULL, 'INT', 'CP', '30 CP ( 2 CX)', 'TOME  1 CP 30 MIN. ANTES DO ALMOÇO E JANTAR POR 30 DIAS ', NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (3, 'PERIDAL 10 MG', NULL, 'INT', 'CP', '60 CP', 'TOME 1 CP 30 MIN. ANTES DO ALMOÇO E JANTAR POR 30 DIAS ', NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (3, 'PLANTABEN', NULL, 'INT', 'SACHE ', '1 CX', 'DISSOLVER O CONTEÚDO DE 1 SACHE EM 1 COPO DE AGUA E TOMAR 1 OU 2 X AO DIA', NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (3, 'TAMARINE 12 MG', '', 'INT', 'CP', ' 1 CX', 'TOME  1 CP  1 X AO DIA ', NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (3, 'PILORY PAC RETRAT', NULL, 'INT', 'CP', ' 1 CX', 'TOMAR  4 CP 30 MIN. ANTES DO CAFÉ E 3 CP 30 MIN. ANTES DO JANTAR POR 10 DIAS ', NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (3, 'PROFLOX 500 MG', NULL, 'INT', 'CP', '14 CP', 'TOMAR 1 CP DE 12/12 HORAS POR 7 DIAS ', NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (3, 'PROBIATOP', NULL, 'INT', 'SACHE ', ' 1 CX', 'DISSOLVER O CONTEÚDO DE 1 SACHE EM 150 ML DE AGUA E TOMAR 1 X AO DIA ', NULL, NULL, NULL, NULL, 'N', 'D');`,
      ` INSERT INTO tab_medicamento (cod_funcionario, nome_medicamento, observacao, uso, forma, quantidade, posologia_1, posologia_2, posologia_3, posologia_4, posologia_5, tp_medicamento, tipo) VALUES (3, 'SIMBIOFLORA', NULL, 'INT', 'SACHE', ' 1 CX', 'DISSOLVER O CONTEÚDO DE 1 SACHE EM 150 EM 1 COPO DE ÁGUA E TOMAR 1 X AO DIA ', NULL, NULL, NULL, NULL, 'N', 'D');`,
    ];
  }
});